services:
  gateway:
    image: gateway:latest
    build:
      context: ./gateway/
    ports:
      - "8080:8080"
    networks: 
      - picshare_network

  user-service:
    image: user-service:latest
    build:
      context: ./services/user-service/
    env_file: "./env/user.env"
    depends_on:
      user-db:
        condition: service_healthy
    networks:
        - picshare_network

  user-db:
    image: postgres:latest
    env_file: ./env/user.env
    volumes: 
    - user-service-data:/var/lib/postgresql
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
        - picshare_network

  feed-service:
    image: feed-service:latest
    build:
      context: ./services/feed-service/
    env_file: "./env/feed.env"
    depends_on:
      feed-db:
        condition: service_healthy
    networks:
        - picshare_network

  feed-db:
    image: postgres:latest
    env_file: ./env/feed.env
    volumes: 
    - feed-service-data:/var/lib/postgresql
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
        - picshare_network
        
  post-service:
    image: post-service:latest
    build:
      context: ./services/post-service/
    env_file: "./env/post.env"
    depends_on:
      post-db:
        condition: service_healthy
    networks:
        - picshare_network

  post-db:
    image: postgres:latest
    env_file: ./env/post.env
    volumes: 
    - post-service-data:/var/lib/postgresql
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
        - picshare_network

  storage-service:
    image: storage-service:latest
    depends_on:
      - minio
    build:
      context: ./services/storage-service/
    networks:
        - picshare_network

  minio:
    image: minio/minio
    container_name: minio
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    networks:
      - picshare_network
    volumes:
      - minio-data:/data

volumes:
  auth-service-data:
  feed-service-data:
  user-service-data:
  post-service-data:
  minio-data:


networks:
  picshare_network:
    driver: bridge
