services:
  auth-service:
    image: quay.io/keycloak/keycloak:latest
    env_file: "./env/auth.env"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7080/health/ready"]
      interval: 15s
      timeout: 2s
      retries: 15
    command: ["start-dev", "--http-port", "7080", "--https-port", "7443"]
    ports:
      - "7080:7080"
      - "7443:7443"
    networks:
        - picshare_network

  auth-db:
    image: postgres:latest
    volumes:
      - auth-service-data:/var/lib/postgresql
    env_file: "./env/auth.env"
    expose:
      - "5432"

    networks:
        - picshare_network

volumes:
  auth-service-data:


networks:
  picshare_network:
    driver: bridge
