services:
  auth-service:
    image: quay.io/keycloak/keycloak:latest
    env_file: "./env/auth.env"
    depends_on:
      auth-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7080/health/ready"]
      interval: 15s
      timeout: 2s
      retries: 15
    command: ["start-dev", "--http-port", "7080", "--https-port", "7443"]
    ports:
      - "7080:7080"
      - "7443:7443"
    networks:
        - picshare_network

  auth-db:
    image: postgres:latest
    volumes:
      - auth-service-data:/var/lib/postgresql # good for postgres 18+
    env_file: "./env/auth.env"
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
        - picshare_network


  user-service:
    image: user-service:latest
    build:
      context: ./services/user-service/
    env_file: "./env/user.env"
    depends_on:
      user-db:
        condition: service_healthy
    networks:
        - picshare_network

  user-db:
    image: postgres:latest
    env_file: ./env/user.env
    volumes: 
    - user-service-data:/var/lib/postgresql
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
        - picshare_network

        
  post-service:
    image: post-service:latest
    build:
      context: ./services/post-service/
    env_file: "./env/post.env"
    depends_on:
      post-db:
        condition: service_healthy
    networks:
        - picshare_network

  post-db:
    image: postgres:latest
    env_file: ./env/post.env
    volumes: 
    - post-service-data:/var/lib/postgresql
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
        - picshare_network


  storage-service:
    image: storage-service:latest
    build:
      context: ./services/storage-service/
    networks:
        - picshare_network

volumes:
  auth-service-data:
  user-service-data:
  post-service-data:


networks:
  picshare_network:
    driver: bridge
