spring:
  application:
    name: Gateway
  services:
    post-service:
      uri: http://post-service:8080
      fallback: placeholder
      path: images/**
    user-service:
      uri: http://user-service:8080
      fallback: placeholder
      path: user/*
    feed-service:
      uri: http://feed-service:8080
      fallback: placeholder
      path: feed/*
